"""add completed_by and effort cols

Revision ID: 0_1_0
Revises: 
Create Date: 2025-07-22 08:58:47.280525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0_1_0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complete_by', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('effort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'effort')
    op.drop_column('task', 'complete_by')
    # ### end Alembic commands ###
