"""switch to date

Revision ID: 0_2_0
Revises: 0_1_0
Create Date: 2025-07-22 09:09:45.171406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0_2_0'
down_revision: Union[str, Sequence[str], None] = '0_1_0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complete_by')
    op.add_column('task', sa.Column('complete_by', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complete_by')
    op.add_column('task', sa.Column('complete_by', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
